# Generated by Django 5.2.16 on 2026-07-17 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_economicevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('broker', models.CharField(blank=True, max_length=120)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True)),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('instrument', models.CharField(choices=[('WIN', 'Mini índice (WIN)'), ('WDO', 'Mini dólar (WDO)'), ('IND', 'Índice cheio (IND)'), ('DOL', 'Dólar cheio (DOL)'), ('STOCK', 'Ação'), ('OTHER', 'Outro')], db_index=True, max_length=12)),
                ('symbol', models.CharField(blank=True, max_length=40)),
                ('setup_label', models.CharField(blank=True, db_index=True, max_length=120)),
                ('direction', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venda')], db_index=True, max_length=8)),
                ('contracts', models.PositiveIntegerField(default=1)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('point_value', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('planned_stop_points', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mae_points', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mfe_points', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('financial_result_override', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('screenshot', models.FileField(blank=True, upload_to='trade_screenshots/%Y/%m/')),
                ('screenshot_url', models.URLField(blank=True, max_length=1000)),
                ('technical_reading', models.TextField(blank=True)),
                ('execution_notes', models.TextField(blank=True)),
                ('emotions_before', models.JSONField(blank=True, default=list)),
                ('emotions_after', models.JSONField(blank=True, default=list)),
                ('discipline_score', models.PositiveSmallIntegerField(default=0)),
                ('technical_quality', models.CharField(choices=[('forced', 'Forçada'), ('weak', 'Fraca'), ('valid', 'Válida'), ('excellent', 'Excelente'), ('unrated', 'Não avaliada')], db_index=True, default='unrated', max_length=16)),
                ('followed_plan', models.BooleanField(blank=True, db_index=True, null=True)),
                ('mistakes', models.JSONField(blank=True, default=list)),
                ('had_relevant_news', models.BooleanField(db_index=True, default=False)),
                ('news_impact', models.CharField(choices=[('none', 'Não impactou'), ('low', 'Impacto leve'), ('medium', 'Impacto moderado'), ('high', 'Impacto forte'), ('unknown', 'Não avaliado')], db_index=True, default='unknown', max_length=12)),
                ('news_notes', models.TextField(blank=True)),
                ('opening_bias', models.CharField(choices=[('buy', 'Comprador'), ('sell', 'Vendedor'), ('neutral', 'Neutro/aguardar'), ('unknown', 'Indisponível')], db_index=True, default='unknown', max_length=12)),
                ('opening_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('opening_matched', models.BooleanField(blank=True, db_index=True, null=True)),
                ('opening_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='dashboard.economicevent')),
                ('market_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='dashboard.marketsnapshot')),
                ('setup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='dashboard.tradesetup')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='dashboard.tradingaccount')),
            ],
            options={
                'ordering': ['-trade_date', '-entry_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('contracts', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=4, max_digits=16)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_exits', to='dashboard.trade')),
            ],
            options={
                'ordering': ['exit_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CapitalMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('deposit', 'Aporte'), ('withdrawal', 'Retirada'), ('adjustment', 'Ajuste')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_movements', to='dashboard.tradingaccount')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('no_trade', models.BooleanField(default=False)),
                ('no_trade_reason', models.CharField(blank=True, max_length=240)),
                ('premarket_notes', models.TextField(blank=True)),
                ('opening_plan', models.TextField(blank=True)),
                ('daily_review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_days', to='dashboard.tradingaccount')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['account', 'trade_date', 'entry_time'], name='trade_acc_date_time_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['setup_label', 'trade_date'], name='trade_setup_date_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalmovement',
            index=models.Index(fields=['account', 'movement_date'], name='dashboard_cap_account_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradingday',
            constraint=models.UniqueConstraint(fields=('account', 'date'), name='unique_trading_day_account_date'),
        ),
    ]
